import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/provider/SidebarProvider";
import BaseLayout from "@/components/Layout/BaseLayout";

const notoSansKr = Noto_Sans_KR({ display: "swap", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKr.className} bg-[#1A1C1E] text-white`}>
        <SidebarProvider>
          <BaseLayout>{children}</BaseLayout>
        </SidebarProvider>
      </body>
    </html>
  );
}
